version: '3.8'

services:
  # front
  todo-front:
    container_name: todo-front
    build:
      context: .
      dockerfile: dockerfile-front
    volumes:
      - "./front/public:/front/public:ro"
      - "./front/src:/front/src:ro"
      - "./front/tsconfig.json:/front/tsconfig.json:ro"
      - "./front/tsconfig.node.json:/front/tsconfig.node.json:ro"
      - "./front/package-lock.json:/front/package-lock.json:ro"
      - "./front/package.json:/front/package.json:ro"
      - "./front/vite.config.ts:/front/vite.config.ts:ro"
      - "./front/node_modules:/front/node_modules"
    command: sh -c "npm ci && npm run dev"
    ports:
      - "3000:3000"
    networks:
      - todo-dev

  # db
  todo-db:
    container_name: todo-db
    image: mysql:8.0
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - "todo-db:/var/lib/mysql"
    ports:
      - "4306:4306"
    networks:
      - todo-dev

  # api
  todo-api:
    container_name: todo-api
    build:
      context: .
      dockerfile: dockerfile-api
    volumes:
      - "./api/bin:/var/www/api/bin"
      - "./api/config:/var/www/api/config"
      - "./api/migrations:/var/www/api/migrations"
      - "./api/public:/var/www/api/public"
      - "./api/src:/var/www/api/src"
      - "./api/templates:/var/www/api/templates"
      - "./api/tests:/var/www/api/tests"
      - "./api/translations:/var/www/api/translations"
      - "./api/var:/var/www/api/var"
      - "./api/vendor:/var/www/api/vendor"
    ports:
      - "9000:9000"
    depends_on:
      - todo-db
    networks:
      - todo-dev

  # nginx
  todo-nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - "./api:/var/www/api"
      - "./nginx-default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - '8080:80'
    depends_on:
      - todo-api
      - todo-db
    networks:
      - todo-dev

  # php my admin
  todo-phpmyadmin:
    container_name: todo-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: todo-db
    depends_on:
      - todo-db
    networks:
      - todo-dev

  # mail
  todo-maildev:
    container_name: todo-maildev
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - todo-dev

networks:
  todo-dev:

volumes:
  todo-db: